- name: Pushing
  docker_image:
   name: test
   repository: soulaymendocker123/livraison
   source: build
   build:         
     path: /var/lib/jenkins/workspace/livraison
   tag: latest
   push: yes
